version: '2'
services:
  web:
    image: odoo:12
    build: ./
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - ./scripts:/var/lib/postgresql/scrips
    ports:
      - "5433:5432"
volumes:
  odoo-web-data:
  odoo-db-data:
